services:
  douyu-keep-just-works:
    image: tophtab/douyu-keep-just-works:latest
    build: .
    container_name: douyu-keep-just-works
    restart: unless-stopped
    ports:
      - '51417:51417'
    volumes:
      - ./config:/app/config
    environment:
      - TZ=Asia/Shanghai
